services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zane
    ports:
      - "5435:5432"
  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    ports:
      - "4985:4983"
    depends_on:
      - db
    environment:
      - STORE_PATH=/app
      - DATABASE_URL=postgresql://postgres:password@db:5432/zane
    volumes:
      - drizzle-gateway-data:/app
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    environment:
      MH_STORAGE: maildir # switch from in-memory to maildir on disk :contentReference[oaicite:0]{index=0}
      MH_MAILDIR_PATH: /mailhog/data # where on the container to store the maildir
    volumes:
      - ./mailhog_data:/mailhog/data

volumes:
  db-data:
  drizzle-gateway-data:
